# Context: same as project name
server.port=8000
server.servlet.context-path=/@project.artifactId@

# Application Details
app.name=@project.artifactId@
app.build.version=@project.version@
app.build.timestamp=@timestamp@

# H2 Database
spring.datasource.url=jdbc:h2:mem:bbl_training_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (local access only)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false